import ListingPage from "@/features/ListingPage";
import { api } from "@/services/api";
import styles from "@/styles/Home.module.css";
import { Inter } from "next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ tracks }: { tracks: any }) {
  return (
    <>
      <Head>
        <title>Fake Deezer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>{" "}
      <main className={`${styles.main} ${inter.className}`}>
        <ListingPage tracks={tracks} />
      </main>{" "}
    </>
  );
}

export async function getServerSideProps() {
  const { data } = await api.get("/editorial/0/charts");
  const { tracks } = data;

  return { props: { tracks } };
}
