import ListingPage from "@/features/ListingPage";
import { TracksResponse } from "@/features/ListingPage/interfaces";
import Providers from "@/lib/Provider";
import { api } from "@/services/api";
import styles from "@/styles/Home.module.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import { GetServerSidePropsContext } from "next/types";

const inter = Inter({ subsets: ["latin"] });

interface Props {
  tracks: TracksResponse;
}

export default function Home({ tracks }: Props) {
  return (
    <>
      <Providers>
        <Head>
          <title>Fake Deezer</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>{" "}
        <main className={`${styles.main} ${inter.className}`}>
          <ListingPage tracks={tracks} />
        </main>{" "}
      </Providers>
    </>
  );
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const { query } = context;
  if (query.search) {
    const { data: tracks } = await api.get("search?q=" + query.search);
    return { props: { tracks } };
  } else {
    const { data } = await api.get("/editorial/0/charts");
    const { tracks } = data;
    return { props: { tracks } };
  }
}
